version: "3.7"

services:
  angular-frontend:
    container_name: frontend-portal
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
  app:
    depends_on:
      - mysqldb
    build: ./styletribute-app
    command: bash -c 'while !</dev/tcp/mysqldb/3306; do sleep 1; done; npm start'
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - UPLOAD_PATH=./uploads
      - UPLOADED_PATH=/styletribute-app/uploads
    stdin_open: true
    tty: true
    volumes:
      - ./uploads:/styletribute-app/uploads

  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
